/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package pv.telas;

import java.sql.Connection;
import java.sql.SQLException;
import java.util.List;
import javax.swing.ImageIcon;
import javax.swing.JDialog;
import javax.swing.JOptionPane;
import net.sf.jasperreports.engine.JRException;
import net.sf.jasperreports.engine.JasperFillManager;
import net.sf.jasperreports.engine.JasperPrint;
import net.sf.jasperreports.swing.JRViewer;
import pv.modelo.Historias;
import pv.modelo.HistoriasLidas;
import pv.modelo.Usuario;
import pv.modelo.dao.ConexaoFactory;
import pv.modelo.dao.HistoriaDAO;
import pv.modelo.dao.UsuarioDAO;

/**
 *
 * @author Gustavo
 */
public class TelaPrincipal extends javax.swing.JFrame {

    /**
     * Creates new form Principal
     */
    public TelaPrincipal() {
        
       
        initComponents();
       
        
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        mensagem = new javax.swing.JLabel();
        imagem = new javax.swing.JLabel();
        jPanel2 = new javax.swing.JPanel();
        jLabel3 = new javax.swing.JLabel();
        userTxt = new javax.swing.JTextField();
        jLabel6 = new javax.swing.JLabel();
        addhistoria = new javax.swing.JTextField();
        botaoinserehisto = new javax.swing.JButton();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        campoSenhaUser = new javax.swing.JPasswordField();
        jButton3 = new javax.swing.JButton();
        botaoRemoveHistoriaBau = new javax.swing.JButton();
        jPanel3 = new javax.swing.JPanel();
        botaoCadastraNovaHistoria = new javax.swing.JButton();
        botaoMostraTodasHistorias = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        buscaHistoria = new javax.swing.JTextField();
        botaoBuscaHistoria = new javax.swing.JButton();
        botaoTrazHistoriasIneditas = new javax.swing.JButton();
        botaoAtualizaHistorinha = new javax.swing.JButton();
        botaoDeletaHistorinha = new javax.swing.JButton();
        botaoAtualizaCadastro = new javax.swing.JButton();
        botaoVisualizaUsers = new javax.swing.JButton();
        botaoDeletaUsers = new javax.swing.JButton();
        campoRecebe = new javax.swing.JLabel();
        jButton4 = new javax.swing.JButton();
        marcaLidas = new javax.swing.JButton();
        recebeImagem = new javax.swing.JLabel();
        desmarcaLidas = new javax.swing.JButton();
        situacao = new javax.swing.JLabel();
        jScrollPane2 = new javax.swing.JScrollPane();
        historia = new javax.swing.JTextPane();
        jMenuBar1 = new javax.swing.JMenuBar();
        jMenu1 = new javax.swing.JMenu();
        ItemMenuGeraRelatorio = new javax.swing.JMenuItem();
        ItemMenuMostraRelatorio = new javax.swing.JMenuItem();
        jMenu3 = new javax.swing.JMenu();
        menuSobre = new javax.swing.JMenu();
        jMenu2 = new javax.swing.JMenu();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Baú de historinhas - Principal");
        setBackground(new java.awt.Color(255, 255, 255));

        mensagem.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        mensagem.setForeground(new java.awt.Color(51, 51, 255));
        mensagem.setText("Baú de historinhas");

        imagem.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagens/bau.jpg"))); // NOI18N

        jPanel2.setBackground(new java.awt.Color(51, 102, 255));
        jPanel2.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "Adicionar historinhas ao seu bau", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, null, new java.awt.Color(255, 255, 255)));
        jPanel2.setForeground(new java.awt.Color(255, 255, 255));

        jLabel3.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(255, 255, 255));
        jLabel3.setText("Informe o nome do usuário:");

        jLabel6.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        jLabel6.setForeground(new java.awt.Color(255, 255, 255));
        jLabel6.setText("Informe o nome da historinha:");

        botaoinserehisto.setText("Adicionar historinha no seu bau");
        botaoinserehisto.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                botaoinserehistoActionPerformed(evt);
            }
        });

        jLabel7.setForeground(new java.awt.Color(255, 255, 255));
        jLabel7.setText("*OBS:Com está opção você poderá cadastrar historinhas para o usuário desejado.");

        jLabel8.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        jLabel8.setForeground(new java.awt.Color(255, 255, 255));
        jLabel8.setText("Informe a senha do usuário :");

        jButton3.setText("Clique aqui para visualizar o baú de historias ");
        jButton3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton3ActionPerformed(evt);
            }
        });

        botaoRemoveHistoriaBau.setText("Deletar historinha no seu bau");
        botaoRemoveHistoriaBau.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                botaoRemoveHistoriaBauActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel7)
                    .addComponent(jButton3)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel8)
                            .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                .addComponent(jLabel6, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(jLabel3, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(botaoinserehisto, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(userTxt)
                            .addComponent(campoSenhaUser)
                            .addComponent(addhistoria, javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(botaoRemoveHistoriaBau, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel3)
                    .addComponent(userTxt, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jLabel8)
                    .addComponent(campoSenhaUser, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(4, 4, 4)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel6)
                    .addComponent(addhistoria, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(botaoinserehisto)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(botaoRemoveHistoriaBau)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel7)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jButton3)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        jPanel3.setBackground(new java.awt.Color(0, 102, 102));
        jPanel3.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "Usuário", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, null, new java.awt.Color(255, 255, 255)));
        jPanel3.setForeground(new java.awt.Color(255, 255, 255));

        botaoCadastraNovaHistoria.setText("Cadastrar nova historinha no sistema");
        botaoCadastraNovaHistoria.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                botaoCadastraNovaHistoriaActionPerformed(evt);
            }
        });

        botaoMostraTodasHistorias.setText("mostrar todas as histórias");
        botaoMostraTodasHistorias.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                botaoMostraTodasHistoriasActionPerformed(evt);
            }
        });

        jLabel1.setForeground(new java.awt.Color(255, 255, 255));
        jLabel1.setText("Digite o nome da historinha");

        botaoBuscaHistoria.setText("Ler História");
        botaoBuscaHistoria.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                botaoBuscaHistoriaActionPerformed(evt);
            }
        });

        botaoTrazHistoriasIneditas.setText("Visualizar historinhas inéditas no sistema");
        botaoTrazHistoriasIneditas.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                botaoTrazHistoriasIneditasActionPerformed(evt);
            }
        });

        botaoAtualizaHistorinha.setText("Atualizar historinha");
        botaoAtualizaHistorinha.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                botaoAtualizaHistorinhaActionPerformed(evt);
            }
        });

        botaoDeletaHistorinha.setText("Deletar historinha");
        botaoDeletaHistorinha.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                botaoDeletaHistorinhaActionPerformed(evt);
            }
        });

        botaoAtualizaCadastro.setText("Atualizar cadastro");
        botaoAtualizaCadastro.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                botaoAtualizaCadastroActionPerformed(evt);
            }
        });

        botaoVisualizaUsers.setText("visualizar usuários cadastrados");
        botaoVisualizaUsers.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                botaoVisualizaUsersActionPerformed(evt);
            }
        });

        botaoDeletaUsers.setText("Deletar seu cadastro");
        botaoDeletaUsers.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                botaoDeletaUsersActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addComponent(jLabel1)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(buscaHistoria, javax.swing.GroupLayout.PREFERRED_SIZE, 134, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(botaoBuscaHistoria))
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                            .addComponent(botaoCadastraNovaHistoria, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(botaoMostraTodasHistorias, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(botaoTrazHistoriasIneditas, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(botaoAtualizaHistorinha, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                        .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel3Layout.createSequentialGroup()
                                .addGap(7, 7, 7)
                                .addComponent(botaoVisualizaUsers, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel3Layout.createSequentialGroup()
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(botaoDeletaHistorinha, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                            .addGroup(jPanel3Layout.createSequentialGroup()
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(botaoDeletaUsers, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(botaoAtualizaCadastro, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))))))
                .addContainerGap())
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel3Layout.createSequentialGroup()
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(buscaHistoria, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(botaoBuscaHistoria))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(botaoMostraTodasHistorias)
                    .addComponent(botaoVisualizaUsers))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(botaoTrazHistoriasIneditas)
                    .addComponent(botaoDeletaHistorinha))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(botaoCadastraNovaHistoria)
                    .addComponent(botaoDeletaUsers))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(botaoAtualizaHistorinha)
                    .addComponent(botaoAtualizaCadastro)))
        );

        campoRecebe.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        campoRecebe.setForeground(new java.awt.Color(0, 0, 153));

        jButton4.setText("Gostei , irei indicar");
        jButton4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton4ActionPerformed(evt);
            }
        });

        marcaLidas.setText("marcar como lida");
        marcaLidas.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                marcaLidasActionPerformed(evt);
            }
        });

        recebeImagem.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);

        desmarcaLidas.setText("Desmarcar como lida");
        desmarcaLidas.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                desmarcaLidasActionPerformed(evt);
            }
        });

        situacao.setFont(new java.awt.Font("Arial", 1, 18)); // NOI18N
        situacao.setForeground(new java.awt.Color(102, 102, 102));

        historia.setEditable(false);
        historia.setBackground(new java.awt.Color(0, 153, 153));
        historia.setFont(new java.awt.Font("Arial", 0, 18)); // NOI18N
        historia.setForeground(new java.awt.Color(102, 102, 102));
        jScrollPane2.setViewportView(historia);

        jMenu1.setText("Relatórios");

        ItemMenuGeraRelatorio.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_R, java.awt.event.InputEvent.CTRL_MASK));
        ItemMenuGeraRelatorio.setText("Gerar relatório");
        ItemMenuGeraRelatorio.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ItemMenuGeraRelatorioActionPerformed(evt);
            }
        });
        jMenu1.add(ItemMenuGeraRelatorio);

        ItemMenuMostraRelatorio.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_S, java.awt.event.InputEvent.CTRL_MASK));
        ItemMenuMostraRelatorio.setText("Visualizar relatório");
        ItemMenuMostraRelatorio.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ItemMenuMostraRelatorioActionPerformed(evt);
            }
        });
        jMenu1.add(ItemMenuMostraRelatorio);

        jMenuBar1.add(jMenu1);

        jMenu3.setText("Ajuda");
        jMenu3.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                jMenu3MousePressed(evt);
            }
        });
        jMenuBar1.add(jMenu3);

        menuSobre.setText("Sobre o baú ");
        menuSobre.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                menuSobreMousePressed(evt);
            }
        });
        jMenuBar1.add(menuSobre);

        jMenu2.setText("Sair");
        jMenu2.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                jMenu2MousePressed(evt);
            }
        });
        jMenuBar1.add(jMenu2);

        setJMenuBar(jMenuBar1);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(imagem)
                        .addGap(18, 18, 18)
                        .addComponent(mensagem, javax.swing.GroupLayout.PREFERRED_SIZE, 236, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(jPanel3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 10, Short.MAX_VALUE)
                .addComponent(recebeImagem, javax.swing.GroupLayout.PREFERRED_SIZE, 210, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(campoRecebe, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addGap(18, 18, 18)
                        .addComponent(situacao))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(marcaLidas)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(desmarcaLidas)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jButton4)
                        .addGap(65, 65, 65))
                    .addComponent(jScrollPane2, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.PREFERRED_SIZE, 431, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(imagem, javax.swing.GroupLayout.Alignment.TRAILING)
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                .addComponent(mensagem, javax.swing.GroupLayout.PREFERRED_SIZE, 69, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(56, 56, 56)))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jPanel3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addContainerGap()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(campoRecebe, javax.swing.GroupLayout.DEFAULT_SIZE, 21, Short.MAX_VALUE)
                            .addComponent(situacao, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(recebeImagem, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jScrollPane2)
                                .addGap(18, 18, 18)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(jButton4)
                                    .addComponent(marcaLidas)
                                    .addComponent(desmarcaLidas))))))
                .addGap(42, 42, 42))
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void botaoBuscaHistoriaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_botaoBuscaHistoriaActionPerformed

        String nomeHistoria = buscaHistoria.getText();

        if (nomeHistoria.equals("")) {

            JOptionPane.showMessageDialog(null, "Informe o nome corretamente");

        } else {
            boolean flag = false;
            HistoriaDAO dao = new HistoriaDAO();
            List<Historias> historias = dao.buscarTodos();
            List<HistoriasLidas> historiasLidas = dao.buscarTodasLidas();
            historia.setContentType("text/html");
            for (int i = 0; i < historias.size(); i++) {

                if (historias.get(i).getNomeHistoria().equalsIgnoreCase(nomeHistoria)) {

                    historia.setText(historias.get(i).getHistoria());
                    //historia.setText(historias.get(i).getHistoria());
                    campoRecebe.setText("Nome da historinha: " + historias.get(i).getNomeHistoria());
                    recebeImagem.setIcon(new ImageIcon(historias.get(i).getFoto()));
                    //System.out.println(historias.get(i).getFoto());
                    flag = true;

                    break;

                }

            }

            if (flag == false) {

                JOptionPane.showMessageDialog(null, "Historinha inexistente , desculpe");
            }

        }

    }//GEN-LAST:event_botaoBuscaHistoriaActionPerformed

    private void botaoCadastraNovaHistoriaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_botaoCadastraNovaHistoriaActionPerformed

        TelaCadastroHistorias tela = new TelaCadastroHistorias();
        tela.setVisible(true);
    }//GEN-LAST:event_botaoCadastraNovaHistoriaActionPerformed

    private int v;
    private void botaoinserehistoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_botaoinserehistoActionPerformed

        HistoriaDAO dao3 = new HistoriaDAO();

        String nomeUser = userTxt.getText();
        String senha = String.valueOf(campoSenhaUser.getPassword());
        String nomeHistorinha = addhistoria.getText();

        boolean flag = false;
        boolean flag2 = false;
        int v2 = 0;
        int v = 0;

        Usuario user = new Usuario();
        Historias hist = new Historias();

        HistoriaDAO dao = new HistoriaDAO();
        UsuarioDAO daoUser = new UsuarioDAO();

        List<Historias> historias = dao.buscarTodos();
        List<Usuario> usuarios = daoUser.buscarTodos();

        for (int i = 0; i < usuarios.size(); i++) {

            if (usuarios.get(i).getNome().equalsIgnoreCase(nomeUser) && usuarios.get(i).getSenha().equalsIgnoreCase(senha)) {
                user.setId(usuarios.get(i).getId());
                flag = true;
                //System.out.println("Vim aqui no for dos user");
                break;
            }

        }

        for (int i = 0; i < historias.size(); i++) {

            if (historias.get(i).getNomeHistoria().equalsIgnoreCase(nomeHistorinha)) {
                hist.setId(historias.get(i).getId());
                //System.out.println("valor do v = " + v);
                flag2 = true;
                break;
            }

        }

        if (flag == true && flag2 == true) {
            dao3.gravaHistoriaProUser(hist, user);
            //userTxt.setText("");
            addhistoria.setText("");
            //campoSenhaUser.setText("");
            JOptionPane.showMessageDialog(null, "Historinha inserida com sucesso em seu bau");

        } else {

            JOptionPane.showMessageDialog(null, "Não foi possível colocar essa história em seu bau");

        }

    }//GEN-LAST:event_botaoinserehistoActionPerformed

    private void jMenu2MousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jMenu2MousePressed
        TelaLoginUsuario telaIni = new TelaLoginUsuario();
        telaIni.setVisible(true);
        this.setVisible(false);
    }//GEN-LAST:event_jMenu2MousePressed

    private void botaoMostraTodasHistoriasActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_botaoMostraTodasHistoriasActionPerformed

        TelaVerTodasHistorias telaVerTodas = new TelaVerTodasHistorias();
        telaVerTodas.setVisible(true);
    }//GEN-LAST:event_botaoMostraTodasHistoriasActionPerformed

    private void marcaLidasActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_marcaLidasActionPerformed
        HistoriaDAO dao = new HistoriaDAO();
        HistoriasLidas historia = new HistoriasLidas();
        List<Historias> historias = dao.buscarTodos();

        for (int i = 0; i < historias.size(); i++) {
            if (historias.get(i).getNomeHistoria().equalsIgnoreCase(buscaHistoria.getText())) {
                historia.setIdHistoria(historias.get(i).getId());
                historia.setLidas(true);
                dao.atualizarLidas(historia);
                JOptionPane.showMessageDialog(null, "Historinha marcada como lida");
                break;
            }

        }

    }//GEN-LAST:event_marcaLidasActionPerformed

    private void jButton3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton3ActionPerformed
        TelaVerBau telaBau = new TelaVerBau();
        telaBau.setVisible(true);

    }//GEN-LAST:event_jButton3ActionPerformed

    private void jButton4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton4ActionPerformed
        HistoriaDAO dao = new HistoriaDAO();
        Historias hist = new Historias();
        List<Historias> historias = dao.buscarTodos();
        for (int i = 0; i < historias.size(); i++) {
            if (historias.get(i).getNomeHistoria().equalsIgnoreCase(buscaHistoria.getText())) {
                hist.setId(historias.get(i).getId());
                hist.setIndicada(historias.get(i).getIndicada() + 1);
                dao.atualizarIndicadas(hist);
                JOptionPane.showMessageDialog(null, "Historinha indicada");
                break;
            }

        }
    }//GEN-LAST:event_jButton4ActionPerformed

    private void desmarcaLidasActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_desmarcaLidasActionPerformed
        HistoriaDAO dao = new HistoriaDAO();
        HistoriasLidas historia = new HistoriasLidas();
        List<Historias> historias = dao.buscarTodos();

        for (int i = 0; i < historias.size(); i++) {
            if (historias.get(i).getNomeHistoria().equalsIgnoreCase(buscaHistoria.getText())) {
                historia.setIdHistoria(historias.get(i).getId());
                historia.setLidas(false);
                dao.atualizarLidas(historia);
                //checaLida.setSelected(false);
                JOptionPane.showMessageDialog(null, "Historinha desmarcada como lida");
                break;
            }

        }

    }//GEN-LAST:event_desmarcaLidasActionPerformed

    private void botaoRemoveHistoriaBauActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_botaoRemoveHistoriaBauActionPerformed

        HistoriaDAO dao3 = new HistoriaDAO();
        String nomeUser = userTxt.getText();
        String senha = String.valueOf(campoSenhaUser.getPassword());
        boolean flag = false;
        boolean flag2 = false;
        int v2 = 0;
        int v = 0;
        String nomeHistorinha = addhistoria.getText();
        Usuario user = new Usuario();
        Historias hist = new Historias();

        HistoriaDAO dao = new HistoriaDAO();
        UsuarioDAO daoUser = new UsuarioDAO();

        List<Historias> historias = dao.buscarTodos();
        List<Usuario> usuarios = daoUser.buscarTodos();

        for (int i = 0; i < usuarios.size(); i++) {

            if (usuarios.get(i).getNome().equalsIgnoreCase(nomeUser) && usuarios.get(i).getSenha().equalsIgnoreCase(senha)) {
                user.setId(usuarios.get(i).getId());
                flag = true;
                //System.out.println("Vim aqui no for dos user");
                break;
            }

        }

        for (int i = 0; i < historias.size(); i++) {

            if (historias.get(i).getNomeHistoria().equalsIgnoreCase(nomeHistorinha)) {
                hist.setId(historias.get(i).getId());
                //System.out.println("valor do v = " + v);
                flag2 = true;
                break;
            }

        }

        if (flag == true && flag2 == true) {
            dao3.DeletaHistoriaProUser(hist, user);
            //userTxt.setText("");
            addhistoria.setText("");
            //campoSenhaUser.setText("");
            JOptionPane.showMessageDialog(null, "Historinha removida com sucesso do seu bau");

        } else {

            JOptionPane.showMessageDialog(null, "Não foi possível remover essa história do seu bau");

        }
    }//GEN-LAST:event_botaoRemoveHistoriaBauActionPerformed

    private void botaoTrazHistoriasIneditasActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_botaoTrazHistoriasIneditasActionPerformed
        TelaVisualizarHistoriasIneditas telaInedita = new TelaVisualizarHistoriasIneditas();
        telaInedita.setVisible(true);
    }//GEN-LAST:event_botaoTrazHistoriasIneditasActionPerformed

    private void ItemMenuGeraRelatorioActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ItemMenuGeraRelatorioActionPerformed
        HistoriaDAO dao = new HistoriaDAO();
        dao.criaRelatorio();
    }//GEN-LAST:event_ItemMenuGeraRelatorioActionPerformed

    private void ItemMenuMostraRelatorioActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ItemMenuMostraRelatorioActionPerformed
       
        Connection conexao = null;
        try {
            String jasper = "jasper/Relatorio Bau de Historinhas.jasper";
            conexao = ConexaoFactory.getConexao();
            JasperPrint print = JasperFillManager.fillReport(jasper, null, conexao);
            JDialog relatorio = new JDialog(this, "Relatório", true); //this é a sua janela principal
            relatorio.getContentPane().add(new JRViewer(print));
            relatorio.pack();
            relatorio.setVisible(true);
        } catch (JRException ex) {
            JOptionPane.showMessageDialog(this, "Problemas na geracao do PDF." + "\n" + ex);
        } finally {
            try {
                if (conexao != null) {
                    conexao.close();
                }
            } catch (SQLException ex) {
                JOptionPane.showMessageDialog(this, "Problemas fechando a conexao com o BD");
            }
        }
    }//GEN-LAST:event_ItemMenuMostraRelatorioActionPerformed

    private void botaoAtualizaHistorinhaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_botaoAtualizaHistorinhaActionPerformed
        
        TelaAtualizarHistoria tela = new TelaAtualizarHistoria();
        tela.setVisible(true);
    }//GEN-LAST:event_botaoAtualizaHistorinhaActionPerformed

    private void botaoVisualizaUsersActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_botaoVisualizaUsersActionPerformed
        TelaVerTodosUsuarios tela = new TelaVerTodosUsuarios();
        tela.setVisible(true);
    }//GEN-LAST:event_botaoVisualizaUsersActionPerformed

    private void botaoDeletaUsersActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_botaoDeletaUsersActionPerformed
        UsuarioDAO dao = new UsuarioDAO();
        if(!dao.buscarTodos().isEmpty()){
            TelaDeletarUsuario tela = new TelaDeletarUsuario();
            tela.setVisible(true);
        }else{
        
            TelaLoginUsuario tela = new TelaLoginUsuario();
            tela.setVisible(true);
            setVisible(false);
        }
    }//GEN-LAST:event_botaoDeletaUsersActionPerformed

    private void botaoDeletaHistorinhaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_botaoDeletaHistorinhaActionPerformed
        
        TelaDeletarHistoria tela = new TelaDeletarHistoria();
        tela.setVisible(true);
        
    }//GEN-LAST:event_botaoDeletaHistorinhaActionPerformed

    private void botaoAtualizaCadastroActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_botaoAtualizaCadastroActionPerformed
        TelaAtualizarUsuario tela = new TelaAtualizarUsuario();
        tela.setVisible(true);
    }//GEN-LAST:event_botaoAtualizaCadastroActionPerformed

    private void menuSobreMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_menuSobreMousePressed
        TelaSobre tela = new TelaSobre();
        tela.setVisible(true);
    }//GEN-LAST:event_menuSobreMousePressed

    private void jMenu3MousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jMenu3MousePressed
        TelaAjuda tela = new TelaAjuda();
        tela.setVisible(true);
    }//GEN-LAST:event_jMenu3MousePressed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(TelaPrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(TelaPrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(TelaPrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(TelaPrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new TelaPrincipal().setVisible(true);

            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JMenuItem ItemMenuGeraRelatorio;
    private javax.swing.JMenuItem ItemMenuMostraRelatorio;
    private javax.swing.JTextField addhistoria;
    private javax.swing.JButton botaoAtualizaCadastro;
    private javax.swing.JButton botaoAtualizaHistorinha;
    private javax.swing.JButton botaoBuscaHistoria;
    private javax.swing.JButton botaoCadastraNovaHistoria;
    private javax.swing.JButton botaoDeletaHistorinha;
    private javax.swing.JButton botaoDeletaUsers;
    private javax.swing.JButton botaoMostraTodasHistorias;
    private javax.swing.JButton botaoRemoveHistoriaBau;
    private javax.swing.JButton botaoTrazHistoriasIneditas;
    private javax.swing.JButton botaoVisualizaUsers;
    private javax.swing.JButton botaoinserehisto;
    private javax.swing.JTextField buscaHistoria;
    private javax.swing.JLabel campoRecebe;
    private javax.swing.JPasswordField campoSenhaUser;
    private javax.swing.JButton desmarcaLidas;
    private javax.swing.JTextPane historia;
    private javax.swing.JLabel imagem;
    private javax.swing.JButton jButton3;
    private javax.swing.JButton jButton4;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JMenu jMenu1;
    private javax.swing.JMenu jMenu2;
    private javax.swing.JMenu jMenu3;
    private javax.swing.JMenuBar jMenuBar1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JButton marcaLidas;
    private javax.swing.JLabel mensagem;
    private javax.swing.JMenu menuSobre;
    private javax.swing.JLabel recebeImagem;
    private javax.swing.JLabel situacao;
    private javax.swing.JTextField userTxt;
    // End of variables declaration//GEN-END:variables
}
